### ISSUE TITLE
Namensvorschläge?

### ISSUE THREAD

**Issue by alex1702** [alex1702/API-Entwurf#1]
Du bist mir auch son FLAPI..Bird xD Sry...das bot sich so an.

**Comment by criztovyl** [comment]
FilmListen API :fish:

**Comment by alex1702** [comment]
Wo wir grad beim Namen sind...
FilmListen API?! Was? Warum? Wieso?
Wofür?

**Comment by jankal** [comment]
@alex1702 Das wird die Umestzung von https://hub.mediathekview.de/content/perma?id=380
Dabei wäre das Endziel, dass im Client eingestellt werden kann, welche Filmlisten geladen werden sollen (zdfneo, 30 Tage Vergangenheit). So, dass der Benutzer sich sozusagen seine Filmliste selbst zusammenkonfigurieren kann... Bsp.: Wer braucht KiKa?

**Comment by alex1702** [comment]
Ok, schön dass schon git flow verwendet wird.

**Comment by jankal** [comment]
Wir sind ja nicht im Zirkus hier...

**Comment by alex1702** [comment]
Wie bitte?

**Comment by jankal** [comment]
Naja... Nur im Zirkus geht's... nun ja... "drunter und drüber"... Also ich meine, das soll ja nicht aussehen, dass es niemand mehr warten kann... man muss ja die Übersicht behalten...

**Comment by alex1702** [comment]
Wie auch immer xD ich werde aber wieder den master sperren nur als vorwarnung xD

**Comment by jankal** [comment]
Gut so... Du kannst ja dann, wenn wir was vorzeigbares in develop haben in den master mergen.

**Comment by alex1702** [comment]
Jup halt bei einem release.

**Comment by alex1702** [comment]
Wäre für MediathekRESTAPI

**Comment by criztovyl** [comment]
Find' ich zu lang.
~~Ich würd' auch anmerken das die API ja nicht für MV als Programm ist, sonder für die Filmliste, MV bspw. wäre ja nur Konsument.
Bei MSearch passt's wiederrum, á la "MediathekSearch".~~ (Hach, ich kann nicht lesen -.-)

**Comment by alex1702** [comment]
Hab es halt auf die Mediathek der öffis bezogen.
Und warum sollte die länge schlimm sein?
FilmlistAPI vllt?

**Comment by criztovyl** [comment]
ÖRAPI

**Comment by alex1702** [comment]
_augen verdreh_ :P
