### ISSUE TITLE
Feature Branche Namen

### ISSUE THREAD

**Issue by criztovyl** [alex1702/API-Entwurf#13]
`feature/#12` bswp. ist doch etwas sehr 'kryptisch', ich würde eher dazu tendieren noch einen Bezeichner hinzuzufügen, bspw `feature/#12-apidoc`.

**Comment by alex1702** [comment]
ich finde es macht es einfacher das weg zu lassen weil man sich nicht um ein namen gedanken machen muss der alles beschreibt was man macht. Und man kann ja jederzeit im issue channel nachsehen was das feature bedeutet. Ich würde sagen man kann es optional machen.

**Comment by criztovyl** [comment]
Einigen wir uns auf optional :)
