### ISSUE TITLE
Datenformat weniger repetitiv

### ISSUE THREAD

**Issue by criztovyl** [alex1702/API-Entwurf#19]
Es ist repetitiv in jeder Controller-Methode auf `?format=:format` zu prüfen.

**Comment by criztovyl** [comment]
WIP

**Comment by jankal** [comment]
Hatte ich auch schon dran gedacht, war aber bisher zu faul xD
Schaut gut aus +1 !

**Comment by jankal** [comment]
Merged!

**Comment by criztovyl** [comment]
#24
