### ISSUE TITLE
Ausgabe komprimieren

### ISSUE THREAD

**Issue by jankal** [alex1702/API-Entwurf#22]
Wir könnten/sollten die Ausgabe mit einer Art von Kompression (z.B. xz) komprimieren.

Dies wäre mit [payden/php-xz](https://github.com/payden/php-xz) möglich.

Leider wird uns payden/php-xz#10 blocken.

**Comment by jankal** [comment]
Möglicherweise könnte ich das übernehmen und auch PHP7-Kompatibel bringen payden/php-xz#11

**Comment by jankal** [comment]
Möglicherweise können wir von hier forken und weitermachen (PHP7): [udan11/php-xz](https://github.com/udan11/php-xz)

**Comment by criztovyl** [comment]
Vorerst sollte einfache Transportkomprimierung reichen.
