### ISSUE TITLE
Einheitlicher PHP-Stil

### ISSUE THREAD

**Issue by jankal** [alex1702/API-Entwurf#27]
Ich glaube, langsam brauchen wir einen Standard, nach welchem der Code in diesem Repo geschrieben wird... bei manchem bekomme ich nämlich Augenkrebs (und der mesitgenutzte Standard auch), wobei auch ich die aktuellen Standards nicht komplett einhalte.

Als Standards wären zu nennen:
* http://www.php-fig.org/psr/psr-1/
* http://www.php-fig.org/psr/psr-2/

**Comment by criztovyl** [comment]
Ich würde die Soft-Tabs an mich nehmen, das ist schnell erledigt, mit der Soft-Width muss ich mal gucken.

**Comment by alex1702** [comment]
soft-tabs?
kruze frage zu den geöffneten geschweiften Klammern. Im PSR ist in der nächsten Zeile vorgegeben. Ich mag sie aber lieber in der gleichen Zeile.
Welche Methode ist euch lieber?

**Comment by criztovyl** [comment]
Soft-Tabs = 4 Leerzeichen als Einrückung. (PSR 2 2.4)
Und: Gleiche Zeile.

**Comment by alex1702** [comment]
Ok also das was ich mir gedacht hatte, thx.
Hoffe das kann ich alles einstellen. Gibt nix schlimmeres als Leerzeichen durchgehen zu müssen xD

**Comment by criztovyl** [comment]
`sed 's/\t/    /g' *`

**Comment by criztovyl** [comment]
Bzw `find -name "*.php" -type f -execdir sed 's/\t/    /g' -i {} \;` :D

**Comment by alex1702** [comment]
Angeber xD :P

**Comment by criztovyl** [comment]
Alles nur zur Doku... behaupte ich jetzt mal. xD
