### ISSUE TITLE
develop als Basisbranch

### ISSUE THREAD

**Issue by criztovyl** [alex1702/API-Entwurf#6]

**Comment by alex1702** [comment]
für entwickler oder anwender gemeint?
Zur entwicklung ist develop der haupt und nur zu einem release wird in den master gemergt.

**Comment by jankal** [comment]
Okay. Würde ich auch sagen. Deshalb gerade #5 done.

**Comment by criztovyl** [comment]
Als Basisbranch für das Repo, als Standart für PRs und für „Diese Branch ist ... hinter master (dann develop)”.
Natürlich ist das dann nicht interessant für Nutzer (ob nu master oder develop als Basisbranch), sie sollten dann mit den Releases komform geh'n :)

**Comment by alex1702** [comment]
Nein, das werde ich nicht machen, da wenn irgendjemand sich das ansieht soll er einen stabilen Branch sehen. Wenn du jetzt Features entwickelst nutze git flow und merge direkt in develop und lade hoch.

**Comment by criztovyl** [comment]
Ukay, auf e

**Comment by criztovyl** [comment]
Ukay, auf ersteres müssen wir uns nur einigen, zweiteres mach ich ja schon so.
Ich halte fest: GitHub Basisbranch bleibt `master`.
(Reopen war nen Fehler, hab den falschen Button gedrückt)

**Comment by alex1702** [comment]
genau und ich habs glaub ich noch nicht explezit genannt: verwende git flow im wiki unter Entwicklung steht alles wichtige.
