### ISSUE TITLE
master mit master-new ersetzen

### ISSUE THREAD

**Issue by criztovyl** [alex1702/API-Entwurf#7]
(Rebased)

**Comment by criztovyl** [comment]
Sinn und Zweck des ganzen ist von Anfang an eine saubere, klare History zu haben.
Da wir noch relativ am Anfang stehen, ist es für mich akzeptabel zu diesem Zeitpunkt lokale Histories durch das Ersetzen (`git push -f`) zu "zerstören", da's bisher nur wenige Leute sind.

**Comment by alex1702** [comment]
erstellst du dafür noch ein pull request?

**Comment by criztovyl** [comment]
Ersetzen geht nicht mit Pull, zeigt auf ne andere History. 
Hab noch nicht gepush, weil sich aus der Diskussion hier für mich noch keine Zustimmung ergab ^^

**Comment by alex1702** [comment]
Also muss ich pushen xD da ich dem master protected habe. Sag mir einfach was ich machen muss.

**Comment by criztovyl** [comment]
```
# Update Metadata
git fetch origin
# Force push master-new auf master auf origin
git push -f origin master-new:master
# Delete master new
git push :master-new
```

**Comment by alex1702** [comment]
ok werde ich machen.
EDIT: wollte ich xD
da er es bei einem protected branch grad nicht erlaubt und master-new auch etwas hinterher hinkt hab ich mich grad doch dagegen entschieden das zu machen.
Ich meine die History ist jetzt nicht so wichtig.

**Comment by criztovyl** [comment]
Doch, ich finde das es wichtig ist.
Und kla' ist das für ne Protected Branch nicht erlaubt, dazu muss sie dann schon wieder entsperrt werden, dann den force-push und dann wieder sperren.

**Comment by criztovyl** [comment]
@alex1702  `master-new` einfach so zu mergen (https://github.com/mediathekview/FLAPI/commit/397248b19d8dc8151aee00f8f73ad06bd59f125e) macht nu' kein' Sinn oO

**Comment by criztovyl** [comment]
`master-new` hinkt mit Absicht zurück, denn an dem Commit (https://github.com/mediathekview/FLAPI/commit/cb6f36f77a393f2d6a69c367a47ea4b2a36d40bc) ist alles auf einem stabilen Stand (Version 0 sozusagen), nämlich einfach nur das standardmäßig generierte Slim Skelett.
Alles danach ist dann nicht zwangsweise Stabil und gehört zur nächstsen Version, also eindeutig auf `develop`.

**Comment by alex1702** [comment]
Ok dann hätte ich auch lokal forcen müssen Okaaaay Kommando auf anfang ich machs nochmal.

**Comment by alex1702** [comment]
Jetzt sollte es passen.

**Comment by criztovyl** [comment]
Thx :heart:
