### ISSUE TITLE
develop mit develop-new ersetzen

### ISSUE THREAD

**Issue by criztovyl** [alex1702/API-Entwurf#8]
(Reabased)

**Comment by alex1702** [comment]
alta was machst du da? xD

**Comment by criztovyl** [comment]
Die History bisher ist nicht so nach meinen Vorstellungen, daher jetzt rebased.
Derzeit ist `git push -f` noch nicht so böse, sind ja noch ganz am Anfang.

**Comment by criztovyl** [comment]
Sinn und Zweck des ganzen ist von Anfang an eine saubere, klare History zu haben.
Da wir noch relativ am Anfang stehen, ist es für mich akzeptabel zu diesem Zeitpunkt lokale Histories durch das Ersetzen (git push -f) zu "zerstören", da's bisher nur wenige Leute sind.

**Comment by alex1702** [comment]
Ok
