### ISSUE TITLE
Exceptions in angefragtem Datenformat

### ISSUE THREAD

**Issue by jankal** [alex1702/API-Entwurf#9]
Aktuell wird bei einem Fehler einfach eine `\Exception` geworfen.

Langzeitziel, bspw. für JSON:
```json
{
    "error": "<error-name>",
    "message": "<error message>"
}
```

**Comment by criztovyl** [comment]
Sollte von `?format=:format` abhängen.

**Comment by jankal** [comment]
Hatte ich auch anfangs: "wie in Dokumentation angegeben"

**Comment by criztovyl** [comment]
Fehler, die das Format betreffen (bspw. ungültiges Format), in Klartext ausgeliefern.

**Comment by criztovyl** [comment]
Ich nehm' mich dem mal an.
